---

driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEY_ID'] %>
  security_group_ids: [ "<%= ENV['AWS_SGROUP_ID'] %>" ]
  region: <%= ENV['AWS_REGION'] %>
  availability_zone: <% ENV['AWS_AVAILABILITY_ZONE'] %>
  instance_type: <%= ENV['AWS_INSTANCE_TYPE'] || 't2.micro' %>
  associate_public_ip: true
  require_chef_omnibus: false
  tags:
    'ansible-role': ansible-role-docker
<% if ENV['AWS_SUBNET'] %>
  subnet_id: <%= ENV['AWS_SUBNET'] %>
<% end %>
<% if ENV['AWS_IAM_PROFILE'] %>
  iam_profile_name: <%= ENV['AWS_IAM_PROFILE'] %>
<% end %>


transport:
  ssh_key: <%= ENV['KITCHEN_SSH_KEY'] %>
  connection_timeout: 120
  connection_retries: 10
  max_ssh_sessions: 4


provisioner:
  name: ansible_playbook
  hosts: docker-hosts
  role_name: docker-engine
  require_ansible_repo: false
  require_ansible_omnibus: true
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ansible_verbose: false
  ansible_verbosity: warn
  idempotency_test: true


verifier:
  name: shell


suites:
  - name: latest
    provisioner:
      playbook: tests/vagrant/latest.yml
    verifier:
      command: PLAYBOOK=tests/vagrant/latest.yml bundle exec rspec -c -f d -I serverspec

  - name: os-engine
    provisioner:
      playbook: tests/cloud/os-engine.yml
    verifier:
      command: PLAYBOOK=tests/cloud/os-engine.yml bundle exec rspec -c -f d -I serverspec

  - name: cs-engine
    excludes:
      - debian-8
      - ubuntu-16.04
    provisioner:
      playbook: tests/cloud/cs-engine.yml
    verifier:
      command: PLAYBOOK=tests/cloud/cs-engine.yml bundle exec rspec -c -f d -I serverspec

  - name: py-pkg
    excludes:
      - ubuntu-14.04
    provisioner:
      playbook: tests/cloud/py-pkg.yml
    verifier:
      command: PLAYBOOK=tests/cloud/py-pkg.yml bundle exec rspec -c -f d -I serverspec

  - name: storage-aufs
    excludes:
      - centos-7
    provisioner:
      playbook: tests/cloud/storage-aufs.yml
    verifier:
      command: PLAYBOOK=tests/cloud/storage-aufs.yml bundle exec rspec -c  -I serverspec

  # The suite block_device_mappings overwrite the platform configuration. To allow for the /dev/sda1
  # volume to be deleted under, it must be configured under suites. This forces the creation of an
  # additional suite when using the ec2 driver
  - name: storage-btrfs-centos
    excludes:
      - debian-8
      - ubuntu-14.04
      - ubuntu-16.04
    driver:
      block_device_mappings:
        - device_name: /dev/sda1
          ebs:
            volume_type: standard
            volume_size: 8
            delete_on_termination: true
        - device_name: /dev/xvdb
          ebs:
            volume_type: standard
            volume_size: 1
            delete_on_termination: true
    provisioner:
      playbook: tests/cloud/storage-btrfs.yml
    verifier:
      command: PLAYBOOK=tests/cloud/storage-btrfs.yml bundle exec rspec -c -f d -I serverspec

  - name: storage-btrfs-debian
    excludes:
      - centos-7
    driver:
      block_device_mappings:
        - device_name: /dev/xvdb
          ebs:
            volume_type: standard
            volume_size: 1
            delete_on_termination: true
    provisioner:
      playbook: tests/cloud/storage-btrfs.yml
    verifier:
      command: PLAYBOOK=tests/cloud/storage-btrfs.yml bundle exec rspec -c -f d -I serverspec

  - name: storage-devicemapper
    excludes:
      - debian-8
      - ubuntu-14.04
      - ubuntu-16.04
    driver:
      block_device_mappings:
        - device_name: /dev/sda1
          ebs:
            volume_type: standard
            volume_size: 8
            delete_on_termination: true
        - device_name: /dev/xvdb
          ebs:
            volume_type: standard
            volume_size: 1
            delete_on_termination: true
    provisioner:
      playbook: tests/cloud/storage-devicemapper.yml
    verifier:
      command: PLAYBOOK=tests/cloud/storage-devicemapper.yml bundle exec rspec -c -f d -I serverspec

  - name: storage-legacy-overlay
    excludes:
      - debian-8
      - ubuntu-14.04
    provisioner:
      playbook: tests/cloud/storage-legacy-overlay.yml
    verifier:
      command: PLAYBOOK=tests/cloud/storage-legacy-overlay.yml bundle exec rspec -c -f d -I serverspec

  - name: storage-overlay2
    excludes:
      - debian-8
      - ubuntu-14.04
      - centos-7
    provisioner:
      playbook: tests/cloud/storage-overlay2.yml
    verifier:
      command: PLAYBOOK=tests/cloud/storage-overlay2.yml bundle exec rspec -c -f d -I serverspec

# Default for centos-7 image is to persist the root volume.
# The below overrides that.
platforms:
  - name: centos-7
    driver:
      block_device_mappings:
        - device_name: /dev/sda1
          ebs:
            volume_type: standard
            volume_size: 8
            delete_on_termination: true
  - name: debian-8
  - name: ubuntu-14.04
  - name: ubuntu-16.04
