---
driver:
  name: vagrant
  vagrantfile_erb: Vagrantfile_local.erb

provisioner:
  name: ansible_playbook
  hosts: docker-hosts
  role_name: docker-engine
  sudo_command: sudo -E -H
  require_ansible_repo: false
  require_ansible_omnibus: false
  require_chef_for_busser: false
  require_ruby_for_busser: false
# disabled omnibus and switched to pip install to workaround python-six related
# dependency issues on Ubuntu 14.04
  require_pip: true
  ansible_version: 2.3.0
  ansible_verbose: true
  ansible_verbosity: warn
  idempotency_test: true

verifier:
  name: shell

transport:
  max_ssh_sessions: 4

suites:
  - name: latest
    provisioner:
      playbook: tests/vagrant/latest.yml
    verifier:
      command: PLAYBOOK=tests/vagrant/latest.yml bundle exec rspec -c -f d -I serverspec

  - name: ce-engine
    provisioner:
      playbook: tests/vagrant/ce-engine.yml
    verifier:
      command: PLAYBOOK=tests/vagrant/ce-engine.yml bundle exec rspec -c -f d -I serverspec

  - name: py-pkg
    excludes:
      - ubuntu-1404
    provisioner:
      playbook: tests/vagrant/py-pkg.yml
    verifier:
      command: PLAYBOOK=tests/vagrant/py-pkg.yml bundle exec rspec -c -f d -I serverspec

  - name: storage-aufs
    excludes:
      - centos-7
    provisioner:
      playbook: tests/vagrant/storage-aufs.yml
    verifier:
      command: PLAYBOOK=tests/vagrant/storage-aufs.yml bundle exec rspec -c -f d -I serverspec

  - name: storage-btrfs
    driver:
      customize:
        createhd:
          filename: "/tmp/#{c.vm.hostname}.vdi"
          format: vdi
          size: 1024
        storagectl:
          name: SATA Controller
          portcount: 2
        storageattach:
          storagectl: SATA Controller
          port: 1
          type: hdd
          medium: "/tmp/#{c.vm.hostname}.vdi"
    provisioner:
      playbook: tests/vagrant/storage-btrfs.yml
    verifier:
      command: PLAYBOOK=tests/vagrant/storage-btrfs.yml bundle exec rspec -c -f d -I serverspec

  - name: storage-devicemapper
    excludes:
      - debian-8
      - ubuntu-1404
      - ubuntu-1604
    driver:
      customize:
        createhd:
          filename: "/tmp/#{c.vm.hostname}.vdi"
          format: vdi
          size: 1024
        storagectl:
          name: SATA Controller
          portcount: 2
        storageattach:
          storagectl: SATA Controller
          port: 1
          type: hdd
          medium: "/tmp/#{c.vm.hostname}.vdi"
    provisioner:
      playbook: tests/vagrant/storage-devicemapper.yml
    verifier:
      command: PLAYBOOK=tests/vagrant/storage-devicemapper.yml bundle exec rspec -c -f d -I serverspec

  - name: storage-legacy-overlay
    excludes:
      - ubuntu-1404
      - debian-8
    provisioner:
      playbook: tests/vagrant/storage-legacy-overlay.yml
    verifier:
      command: PLAYBOOK=tests/vagrant/storage-legacy-overlay.yml bundle exec rspec -c -f d -I serverspec

  - name: storage-overlay2
    excludes:
      - ubuntu-1404
      - debian-8
      - centos-7
    provisioner:
      playbook: tests/vagrant/storage-overlay2.yml
    verifier:
      command: PLAYBOOK=tests/vagrant/storage-overlay2.yml bundle exec rspec -c -f d -I serverspec


platforms:
  - name: centos-7
    driver_config:
      box: bento/centos-7.3
      box_url: https://atlas.hashicorp.com/bento/boxes/centos-7.3

  - name: debian-8
    driver_config:
      box: bento/debian-8.7
      box_url: https://atlas.hashicorp.com/bento/debian-8.7

  - name: ubuntu-1404
    driver_config:
      box: bento/ubuntu-14.04
      box_url: https://atlas.hashicorp.com/bento/ubuntu-14.04

  - name: ubuntu-1604
    driver_config:
      box: bento/ubuntu-16.04
      box_url: https://atlas.hashicorp.com/bento/ubuntu-16.04
