---

- name: Manage Container Images
  docker_image:
    api_version: '{{ item.api_version|default(omit) }}'
    archive_path: '{{ item.archive_path|default(omit) }}'
    buildargs: '{{ item.buildargs|default(omit) }}'
    build_path: '{{ item.build_path|default(omit) }}'
    cacert_path: '{{ item.cacert_path|default(omit) }}'
    cert_path: '{{ item.cert_path|default(omit) }}'
    container_limits: '{{ item.container_limits|default(omit) }}'
    docker_api_version: '{{ item.docker_api_version|default(omit) }}'
    docker_host: '{{ item.docker_host|default(omit) }}'
    docker_url: '{{ item.docker_url|default(omit) }}'
    dockerfile: '{{ item.dockerfile|default(omit) }}'
    force: '{{ item.force|default(omit) }}'
    http_timeout: '{{ item.http_timeout|default(omit) }}'
    key_path: '{{ item.key_path|default(omit) }}'
    load_path: '{{ item.load_path|default(omit) }}'
    name: '{{ item.name }}'
    nocache: '{{ item.nocache|default(omit) }}'
    path: '{{ item.path|default(omit) }}'
    pull: '{{ item.pull|default(omit) }}'
    push: '{{ item.push|default(omit) }}'
    repository: '{{ item.repository|default(omit) }}'
    rm: '{{ item.rm|default(omit) }}'
    ssl_version: '{{ item.ssl_version|default(omit) }}'
    state: '{{ item.state|default(omit) }}'
    tag: '{{ item.tag|default(omit) }}'
    timeout: '{{ item.timeout|default(omit) }}'
    tls: '{{ item.tls|default(omit) }}'
    tls_ca_cert: '{{ item.tls_ca_cert|default(omit) }}'
    tls_client_cert: '{{ item.tls_client_cert|default(omit) }}'
    tls_client_key: '{{ item.tls_client_key|default(omit) }}'
    tls_hostname: '{{ item.tls_hostname|default(omit) }}'
    tls_verify: '{{ item.tls_verify|default(omit) }}'
  with_items: '{{ docker_images|default([]) }}'
