---

- name: Configure Docker Engine Repo
  include: '{{ ansible_os_family|lower }}/repo.yml'
  when: docker_manage_engine_repo|bool == true

- name: Install and Configure Docker Engine
  include: '{{ ansible_os_family|lower }}/engine_install.yml'

- name: Configure Docker Engine Users and Groups
  include: 'users_and_groups.yml'
  when: (docker_manage_engine_users|bool == true) and (docker_engine_users is defined)
