---

- name: INSTALL - USERS - Create Docker Engine Group
  group: name=docker system=yes state=present

- name: INSTALL - USERS - Add Users to Docker Engine group
  user: name='{{ item }}' append=yes groups=docker state=present
  with_items: '{{ docker_engine_users|default([]) }}'
