---

- name: Install docker-py package
  package: name='{{ _docker_py_pkg[ansible_os_family|lower] }}' state=present
  register: _external_dependency_success
  until: _external_dependency_success|success
  retries: '{{ external_dependency_retries }}'
  delay: '{{ external_dependency_delay }}'
