---

- name: INSTALL - REPO - Test if apt-transport-https is installed
  command: dpkg-query -l apt-transport-https
  register: _docker_engine_repo_ath
  changed_when: _docker_engine_repo_ath.rc != 0
  ignore_errors: true

- name: INSTALL - REPO - Test if ca-certificates is installed
  command: dpkg-query -l ca-certificates
  register: _docker_engine_repo_cc
  changed_when: _docker_engine_repo_cc.rc != 0
  ignore_errors: true

- name: INSTALL - REPO - Update Apt Cache
  apt: update_cache=yes
  register: _external_dependency_success
  until: _external_dependency_success|success
  retries: '{{ external_dependency_retries }}'
  delay: '{{ external_dependency_delay }}'
  when: (_docker_engine_repo_ath.rc != 0) or
        (_docker_engine_repo_cc.rc != 0)

- name: INSTALL - REPO - Install Repo prereqs
  apt: name='{{ item }}'
  register: _external_dependency_success
  until: _external_dependency_success|success
  retries: '{{ external_dependency_retries }}'
  delay: '{{ external_dependency_delay }}'
  with_items:
    - apt-transport-https
    - ca-certificates
  when: (_docker_engine_repo_ath.rc != 0) or
        (_docker_engine_repo_cc.rc != 0)

- name: INSTALL - REPO - Add Docker CE Repo GPG key
  apt_key:
    keyserver: '{{ docker_engine_repo_gpg_key_server }}'
    id: '{{ docker_engine_repo_ce_deb_gpg_key }}'
  register: _external_dependency_success
  until: _external_dependency_success|success
  retries: '{{ external_dependency_retries }}'
  delay: '{{ external_dependency_delay }}'
  when: (docker_engine_edition|lower != 'enterprise') and
        (docker_engine_edition|lower != 'ee')

- name: INSTALL - REPO - Add Docker Repo
  template:
    src: templates/engine/apt_docker_engine_repo.j2
    dest: /etc/apt/sources.list.d/docker.list
    owner: root
    group: root
    mode: '0644'
  register: _docker_engine_repo_apt_cache

- name: INSTALL - REPO - Update Cache to Add Docker Repo
  apt: update_cache=yes
  register: _external_dependency_success
  until: _external_dependency_success|success
  retries: '{{ external_dependency_retries }}'
  delay: '{{ external_dependency_delay }}'
  when: _docker_engine_repo_apt_cache.changed
